name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: gsumithub
          outputs: dist/snake.svg?raw=true

      - name: Upload Snake
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg

      - name: Commit Snake
        run: |
          mkdir -p assets
          cp dist/snake.svg assets/snake.svg
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update snake"
