name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # update daily
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: gsumithub
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Commit Snake File
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Snake Animation"
          file_pattern: output/*.svg
