name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"     # Daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # USER
          user: gsumithub
          timezone: Asia/Kolkata

          # THEME (Minimal White / Apple Style)
          template: classic
          config_display: large
          config_padding: 12px
          config_border: off
          config_animations: yes
          config_theme: light

          # SECTIONS
          base: header, activity, community, repositories

          # OUTPUT
          filename: stats/metrics.svg
          clean: true
          optimize: true
          output_action: commit

          # LANGUAGES
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_indepth: yes
          plugin_languages_limit: 10
          plugin_languages_other: no
          plugin_languages_details: percentage
          plugin_languages_ignored: ""
          plugin_languages_categories: markup, programming
          plugin_languages_aliases: |
            **/*.html: HTML
            **/*.css: CSS
            **/*.js: JavaScript

          # CALENDAR + FOLLOWUP
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full

          plugin_followup: yes
          plugin_followup_sections: repositories
