name: GitHub Stats Generator

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate metrics.svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # ---------------------------------
          # REQUIRED OR PLUGINS WILL NOT SHOW
          # ---------------------------------
          user: gsumithub
          template: classic
          base: header, activity, community, repositories
          filename: stats/metrics.svg
          output_action: commit
          clean: true
          optimize: true
          config_timezone: Asia/Kolkata

          # Aesthetic + visible plugins
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 10
          plugin_languages_ignored: html, css

          plugin_lines: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full

          plugin_topics: yes
          plugin_topics_mode: starred
          plugin_topics_limit: 15

          plugin_followup: yes
          plugin_followup_sections: repositories, users

          # Reliability
          retries: 3
          retries_delay: 180
