name: GitHub Executive Dashboard

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Custom Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # USER
          user: gsumithub
          config_timezone: Asia/Kolkata

          # CLEAN GLASS STYLE
          template: classic
          config_theme: light
          config_display: large
          config_padding: 16px
          config_border: no
          config_animations: yes

          # MINIMAL BASE
          base: activity, repositories, metadata

          # FOCUS PLUGINS
          plugin_stars: yes
          plugin_repositories: yes
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_indepth: yes
          plugin_languages_categories: markup, programming
          plugin_languages_details: percentage
          plugin_languages_other: no

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 30

          plugin_isocalendar: no
          plugin_followup: no

          # OUTPUT
          filename: stats/executive-metrics.svg
          clean: true
          optimize: true
          output_action: commit
