name: Modern Dev Dashboard

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Modern Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: gsumithub
          config_timezone: Asia/Kolkata

          # CLEAN MODERN STYLE
          template: classic
          config_theme: light
          config_display: large
          config_padding: 20px
          config_border: no
          config_animations: yes

      
          base: metadata

          # ðŸ”¥ STREAK FOCUS
          plugin_streak: yes
          plugin_streak_days: 30

         
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_from: 200

        
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_limit: 6
          plugin_languages_other: no
          plugin_languages_details: percentage

      
          plugin_followup: no
          plugin_repositories: no
          plugin_isocalendar: no
          plugin_topics: no
          plugin_stars: no

          filename: stats/modern-metrics.svg
          clean: true
          optimize: true
          output_action: commit
