name: Generate GitHub Stats
on:
  schedule:
    - cron: "0 * * * *" # auto-update every hour
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Stats
        uses: jaywcjlove/github-action-generate-svg@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: ./stats/
          committer_email: "github-actions[bot]@users.noreply.github.com"
          committer_name: "github-actions[bot]"
