name: Generate GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # updates every 6 hours

jobs:
  github-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Overview & Language Stats
        uses: jaywcjlove/github-action-generate-svg@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: stats/

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update GitHub Stats"
          file_pattern: stats/*.svg
